### ISSUE TITLE
COM exception in VS 2022 when running T4 template

### ISSUE THREAD

**Issue by mdissel** [dotnet/ResXResourceManager#439] opened 2021-12-03 13:31 UTC
Right click on *.tt file and Run Custom Tool.
![image](https://user-images.githubusercontent.com/126084/144610630-fd58b226-6549-4015-91a6-469666b90a7a.png)

Using the default tt file
```
<#@ template debug="false" hostspecific="true" language="C#" #>
<#@ include file="$(SolutionDir)Resources.Designer.t4" #>

```

and the Resource.Designer.t4 is adjusted with the VS2022 change.

```
<#@ assembly name="System.Core" #>
<#@ assembly name="System.Windows.Forms" #>
<#@ assembly name="EnvDTE" #>
<#@ assembly name="EnvDTE80" #>
<#@ assembly name="Microsoft.VisualStudio.Interop" #> 
<#@ import namespace="EnvDTE" #>
<#@ import namespace="EnvDTE80" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Resources" #>
<#@ import namespace="System.Collections" #>
<#@ import namespace="System.ComponentModel.Design" #>
<#@ output extension=".cs" #><#

```

```
Running transformation: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'EnvDTE.ProjectItem'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0B48100A-473E-433C-AB8F-66B9739AB620}' failed due to the following error: Interface wordt niet ondersteund (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.VisualStudio.TextTemplating4029414848B7C1897EADBA643E5DBF87B19A2DFDCAF1E1F45D4261EAC8A25B6AAC66B2C5055D2ECAA5B9A6C6E850374E58A4564BC3F117055B78A939F7CE5797.GeneratedTextTransformation.GetResxProjectItem()
   at Microsoft.VisualStudio.TextTemplating4029414848B7C1897EADBA643E5DBF87B19A2DFDCAF1E1F45D4261EAC8A25B6AAC66B2C5055D2ECAA5B9A6C6E850374E58A4564BC3F117055B78A939F7CE5797.GeneratedTextTransformation.TransformText()	ClassLibrary1	...source\repos\ClassLibrary1\ClassLibrary1\Test.Designer.tt	1	

```

**Comment by tom-englert** [comment] 2021-12-06 06:55
Duplicate of #438

**Closed by tom-englert** 2021-12-06 06:55 UTC
