### ISSUE TITLE
Save Credentials API Key doesn't save.

### ISSUE THREAD

**Issue by leigh-pointer** [dotnet/ResXResourceManager#490] opened 2022-07-29 07:12 UTC
**Describe the bug**
Selecting Save Credentials on Google (the only one I use) API Key doesn't save the credentials.  When reopen VS they are gone. 

**To Reproduce**
Try saving credentials

**Expected behavior**
Credential to be saved.

**Comment by tom-englert** [comment] 2022-07-31 12:00
Tried to restart five times, but could not reproduce. Please provide more details.

**Comment by tom-englert** [comment] 2022-07-31 13:39
Actually when you have a solution open, the configuration is stored in the solution, so your credentials will be only available when this solution is open.
Closing the solution before adding your credentials should fix this.

**Closed** 2022-07-31 13:42 UTC
