### ISSUE TITLE
ResXManager doesn't update *.Designer.cs

### ISSUE THREAD

**Issue by akghasemi** [dotnet/ResXResourceManager#539] opened 2023-03-05 13:21 UTC
I have a monogame project and I used ResXManager for a while on it and it was working fine, since I upgraded project to .net  6, it doesn't update Designer.cs file and I have to modify the file manually. I am not sure how can I diagnostic the problem.
I checked ResXManager logs in output window of visual studio but I don't see any error or log that it shows me that it can't find cs file.
I also checked these things *.Designer.cs is not readonly,
reset all ResXManager settings with reinstalling.
Thanks in advance

**Comment by tom-englert** [comment] 2023-03-06 06:32
Duplicate of #537

**Closed** 2023-03-06 06:33 UTC
Labels: duplicate
