### ISSUE TITLE
Auto translation incomplete / no output?

### ISSUE THREAD

**Issue by josh2112** [dotnet/ResXResourceManager#315] opened 2020-05-12 14:02 UTC
First of all, thanks for this extension! It has been very helpful in pulling out translatable strings from my source and managing multiple ResX files.

I'm now attempting the auto translation using the Google API. In a test project, I have 3 neutral (Englilsh) keys along with French and German ResX files. Only the Google translator is enabled, and I have both German and French targets selected. When I hit "Start" I get German translations for the three keys but no French:

![image](https://user-images.githubusercontent.com/739972/81700899-49c54a80-9437-11ea-8b88-302c37d9d1e0.png)

Hitting "Discard" then "Start" again always results in the same thing: German translations but no French. ~~Furthermore, Wireshark doesn't show any requests being made to translation.googleapis.com.~~ EDITL scratch that, the requests are HTTPS.

Can anyone tell me what's going on?

**Comment by josh2112** [comment] 2020-05-12 14:12
It appears that if I select one language at a time, it works.

I guess it could be made clearer that when you select multiple targets only the first will be translated! Otherwise, close bug I guess.

**Comment by rickbeddard** [comment] 2020-05-12 16:35
Duplicate of #307

**Closed** 2020-05-19 06:57 UTC
