### ISSUE TITLE
Fatal error while translating

### ISSUE THREAD

**Issue by edika99** [dotnet/ResXResourceManager#583] opened 2023-09-27 08:55 UTC
Sometimes while translating a fatal error is thrown that casue the hang of Visual Studio.
For translation  I'm using Google with a regular API key, but I suspect that the error is not related to the kinf of transalation service used.
I've not notice any particular situation when the error happen. Is not thrown in a particular project, nor particular kind of language. 

Visual Studio Community 2022 Version 17.7.0

here is the Stack of the error thrown by visual studio:

```
System.ArgumentNullException
  HResult=0x80004003
  Messaggio=Il valore non può essere null.
Nome parametro: item
  Origine=PresentationFramework
  Analisi dello stack:
   in System.Windows.Automation.Peers.DataGridItemAutomationPeer..ctor(Object item, DataGridAutomationPeer dataGridPeer)
   in System.Windows.Automation.Peers.DataGridAutomationPeer.CreateItemAutomationPeer(Object item)
   in System.Windows.Automation.Peers.ItemsControlAutomationPeer.GetChildrenCore()
   in System.Windows.Automation.Peers.DataGridAutomationPeer.GetChildrenCore()
   in System.Windows.Automation.Peers.AutomationPeer.EnsureChildren()
   in System.Windows.Automation.Peers.AutomationPeer.GetChildren()
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.isDescendantOf(AutomationPeer parent)
   in System.Windows.Automation.Peers.AutomationPeer.ValidateConnected(AutomationPeer connectedPeer)
   in MS.Internal.Automation.ElementProxy.StaticWrap(AutomationPeer peer, AutomationPeer referencePeer)
   in System.Windows.Automation.Peers.AutomationPeer.RaisePropertyChangedEvent(AutomationProperty property, Object oldValue, Object newValue)
   in System.Windows.Automation.Peers.ComboBoxAutomationPeer.RaiseValuePropertyChangedEvent(String oldValue, String newValue)
   in System.Windows.Controls.ComboBox.OnTextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   in System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   in System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   in System.Windows.Data.BindingExpression.Activate(Object item)
   in System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
   in System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.TreeWalkHelper.OnInheritablePropertyChanged(DependencyObject d, InheritablePropertyChangeInfo info, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   in System.Windows.Controls.ContentPresenter.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   in System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   in System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   in System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   in System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   in System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   in System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   in System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty(TreeChangeInfo info, DependencyObject d, FrameworkObject& fo, DependencyProperty dp, FrameworkPropertyMetadata fMetadata, Style selfStyle, Style selfThemeStyle, ChildRecord& childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   in System.Windows.TreeWalkHelper.InvalidateTreeDependentProperties(TreeChangeInfo info, FrameworkElement fe, FrameworkContentElement fce, Style selfStyle, Style selfThemeStyle, ChildRecord& childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   in System.Windows.FrameworkElement.InvalidateTreeDependentProperties(TreeChangeInfo parentTreeState, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   in System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
   in System.Windows.TreeWalkHelper.OnAncestorChanged(DependencyObject d, TreeChangeInfo info, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   in System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   in System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   in System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   in MS.Internal.PrePostDescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   in System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
   in System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
   in System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   in System.Windows.Media.Visual.RemoveVisualChild(Visual child)
   in System.Windows.Media.VisualCollection.DisconnectChild(Int32 index)
   in System.Windows.Media.VisualCollection.InternalRemove(Visual visual)
   in System.Windows.Controls.UIElementCollection.RemoveNoVerify(UIElement element)
   in System.Windows.Controls.VirtualizingStackPanel.DisconnectRecycledContainers()
   in System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   in System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   in System.Windows.Controls.Primitives.DataGridRowsPresenter.MeasureOverride(Size constraint)
   in System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   in System.Windows.UIElement.Measure(Size availableSize)
   in System.Windows.ContextLayoutManager.UpdateLayout()
   in System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   in System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   in System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   in System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.DispatcherOperation.InvokeImpl()
   in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Windows.Threading.DispatcherOperation.Invoke()
   in System.Windows.Threading.Dispatcher.ProcessQueue()
   in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by tom-englert** [comment] 2023-09-28 09:35
Duplicate of #430
This is a bug in WPF, there is nothing we can do about this, and Microsoft refused to fix this in NetFramework: https://github.com/dotnet/wpf/issues/5428

**Closed by tom-englert** 2023-09-28 09:35 UTC
