### ISSUE TITLE
Resource Files with duplicate Project, File, and Key

### ISSUE THREAD

**Issue by Darkseal** [dotnet/ResXResourceManager#494] opened 2022-08-27 00:51 UTC
Hello there,

I'm currently evaluating this tool to ease the translation of a couple ASP.NET Core projects (~1000 resource entries). First of all, thank you for having done this - it was precisely what I was looking for!

That said, while trying it I've noticed an odd behavior that raises some concerns: if I perform the export, the resulting MS Excel export file doesn't have a column containing the full `path + filename` of the various resource files, or any distinctive unique name that can be used to uniquely identify them. I only see `Project`, `File`, and `Key` columns, none of which is necessarily unique (even combined).

Given the above, how can the tool distinguish between two (or more) different resx files having the same `Project`, `File`, and `Key` values, but a different path?

For example, consider the following three resource files:

* /Views/Home/Index.en.resx
* /Views/Shop/Index.en.resx
* /Views/Community/Index.en.resx

The above files all have the same `Project` value (since they all belong to the same project), and the same `Name` value (which is `Index`); moreover, they could even share some `Key` values, since keys must only be unique within a single resx file (same key names in different resx files are allowed).

Now, suppose I only want to export _one_ of these three files, change some of its resource values (possibly even adding new keys and/or deleting existing keys), and then import back the modified MS Excel file. Will the software be able to properly identify the correct "source" resx file I have exported and only update that file, leaving the other files untouched?  And if so, how does it do it?

Please let me know, thanks!

**Comment by tom-englert** [comment] 2022-08-27 10:44
Did you try and it failed?

**Comment by Darkseal** [comment] 2022-08-27 17:59
Yes. As a matter of fact, it didn't "fail": it imported all the keys in the first .resx file, leaving the rest as they were.

I think we might have a non-trivial issue here, unless I did something wrong: in my opinion, it could be easily fixed by adding the project-relative resx file path in the `Name` column (or just adding another column, like `Path`, and use that to localize the proper file).

Please let me know your thoughts on that.

**Comment by tom-englert** [comment] 2022-08-28 06:11
I'm not sure what you are doing, but when I export it looks like this:
![image](https://user-images.githubusercontent.com/10229954/187060329-b361110c-a717-4dd9-8d3c-00b16a7e787e.png)

**Comment by Darkseal** [comment] 2022-08-28 11:28
It seems that your export already contain the project-relative path of the resource in column B, which absence is what causes all the trouble in my export/import process. 

However, mine doesn't. Here's the screenshot of my project's resx structure:

![ss_01](https://user-images.githubusercontent.com/530429/187071630-7246dac6-962d-485f-a508-67e373a7847f.jpg)

And here's the screenshot of the resulting Excel export for these selected files: 

![ss_02](https://user-images.githubusercontent.com/530429/187071765-041dbdd8-a660-4f04-a7fc-22c3e034735f.jpg)

Notice the absence of the full path in column B: it's the same `Index` value for all the four (different) .resx files. Maybe there's a way to enable/disable the project-relative path segment, which I did miss?

Please let me know, thanks

**Comment by Darkseal** [comment] 2022-08-28 12:23
**UPDATE**: I've noticed that I only have this issue in the VS2022 extension - the standalone app looks fine and the project-relative path is present.

VS2022 extension screenshot:

![ss-01](https://user-images.githubusercontent.com/530429/187073952-afc3b03e-f132-40d2-94b3-359d7f977fcd.jpg)

Standalone version screenshot (same project):

![ss-02](https://user-images.githubusercontent.com/530429/187073981-b0f6e0e7-3b9c-4a69-b18d-b3e4694f7aae.jpg)

It seems that there's something wrong in the VS2002 extension version while calculating the resource file's `uniqueName`, which doesn't happen in the standalone version.

**Comment by tom-englert** [comment] 2022-08-30 10:37
In the VSIX the unique name comes from Visual Studio.
Also I don't see any neutral resources, that can't work anyhow.

**Comment by Darkseal** [comment] 2022-08-30 13:43
Neutral resources are not an issue there (keys are neutral resources): I think that the issue lies in the uniqueName, which in my scenario doesn't include the project-relative path (don't know why). However, since the stand-alone app doesn't have this issue and it seems like I'm the only one experiencing this in the VSIX, I think I'll just use the stand-alone app and get it solved like that :)

Thanks again for the support

**Comment by VladDragnea** [comment] 2022-09-18 11:43
Hi all,
I was also reviewing this tool (which is great, btw) for using with a WPF solution with lots of resource files. I've run into the same kind of issue while exporting resources, and noticed that it's happening for projects that are outside the path of the solution.
The problem is caused by the inability to get the path of a project file relative to the solution root in a situation like the one previously mentioned.
I've submitted a PR with a fix for this issue (#495).

**Comment by tom-englert** [comment] 2022-09-18 12:58
Fixed by #495

**Closed by tom-englert** 2022-09-18 12:58 UTC
