### ISSUE TITLE
DeepL Translation does not work with free API Tier

### ISSUE THREAD

**Issue by TobiOfGaming** [dotnet/ResXResourceManager#408] opened 2021-05-07 06:30 UTC
I have an API Key for the Free Version of the Deepl API. As the endpoint of the Pro Version differs from the one of the Free Version, i can not use the DeepL Translation feature. (curl - Pro Version:  https://api.deepl.com/v2/translate;   curl - Free Version: https://api-free.deepl.com/v2/translate) In the DeepLTranslator.cs Class the url of the Pro Version is used. It would be very helpfull, if you could change the endpoints at the UI Level.

**Comment by tom-englert** [comment] 2021-05-07 09:36
Duplicate of #405

**Closed by tom-englert** 2021-05-07 09:36 UTC
Labels: duplicate
