### ISSUE TITLE
Standalone Application: List of recently used directories / favorites

### ISSUE THREAD

**Issue by alex3683** [dotnet/ResXResourceManager#613] opened 2023-11-23 16:00 UTC
**Is your feature request related to a problem? Please describe.**

I'm usually working with multiple clones of my project, one for the current develop branch, one for the release branch and one for temporary switching between different branches. Thus when working with translation files I have to switch the directory quite often.

**Describe the solution you'd like**

It would be nice if there would be a selection for recently used directories or a favorites list of directories here:

![grafik](https://github.com/dotnet/ResXResourceManager/assets/768322/96ae154c-17a2-417f-8c6b-0969bd13fc4e)

**Describe alternatives you've considered**

I only know about selecting a directory every time manually.

**Additional context**

See above.

**Comment by etherfield** [comment] 2023-11-24 14:15
Seems to be a duplicate of #507

**Closed** 2023-11-25 16:26 UTC
Labels: Feature request, Up for grabs

**Comment by alex3683** [comment] 2023-12-05 09:52
Oh, just saw what I did here. Sorry, it was not my intentation to spam you, but obviously this was still an issue for me two years later :-D
