### ISSUE TITLE
Azure : Could not load file or assembly 'HtmlAgilityPack' Version 1.11.36.0

### ISSUE THREAD

**Issue by akbalburak** [dotnet/ResXResourceManager#427] opened 2021-09-19 15:50 UTC
**Describe the bug**
Hi, Whenever i would like to translate with azure api.
The exception in the title occured.
Note : When automatically detect html tag is selected.

**Comment by tom-englert** [comment] 2021-09-19 16:30
Duplicate of #426

**Comment by tom-englert** [comment] 2021-09-19 16:31
Already fixed.

**Closed by tom-englert** 2021-09-19 16:30 UTC
Labels: duplicate
