### ISSUE TITLE
Xliff sync state

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/ResXResourceManager#586] opened 2023-10-24 08:43 UTC
**Describe the bug**
If a xliff resource state has been set to final, but the source resx is changed, the state in the xliff should be updated to 'needs-review-translation'

**Expected behavior**
When the source resx changes the xliff state should be updated too 'needs-review-translation'

**Comment by tom-englert** [comment] 2023-10-24 15:13
Can't reproduce - when I change the resx, state in xliff goes to` needs-review-translation`

**Comment by IeuanWalker** [comment] 2023-10-24 18:46
@tom-englert the issue is when changing the source resx.

When you alter text in the resx file, the corresponding xliff source is updated with the new text, but the xliff state remains unchanged

**Comment by IeuanWalker** [comment] 2023-10-24 18:59
@tom-englert strange here is a vid of the issue happening 

https://github.com/dotnet/ResXResourceManager/assets/6544051/20655ff6-342e-4c54-9643-9f0707cf1aaf


https://github.com/dotnet/ResXResourceManager/assets/6544051/c6e56ec2-35b2-495b-9f01-0e4246c1a200

Here is the project im testing with in the videos _(its a .net MAUI project, so not sure youd have the stuff installed to build it)_
[MultilingualTest.zip](https://github.com/dotnet/ResXResourceManager/files/13126089/MultilingualTest.zip)

**Comment by tom-englert** [comment] 2023-10-25 11:55
I see, you are changing the neutral text, and then all translations need to be marked as "need review". 
I'll have a look on this.

**Comment by tom-englert** [comment] 2023-10-25 14:39
Your xlif file is invalid:
```xml
<target state="Final">WTest1</target>
```
values are case sensitive, as soon as you change the state to `final` it works.
```xml
<target state="final">WTest1</target>
```

**Closed by tom-englert** 2023-10-25 14:39 UTC

**Comment by IeuanWalker** [comment] 2023-10-25 14:45
@tom-englert ahh, thanks for spotting that
