### ISSUE TITLE
switching to Text template code generator not working in VS 2022

### ISSUE THREAD

**Issue by mdissel** [dotnet/ResXResourceManager#438] opened 2021-12-03 11:36 UTC
I have an existing project with the default PublicResXFileCodeGenerator provider for Resx files. When I open the resX resource manager in Visual Studio, select the file and select Text Template, the global file is added to the solution, the Resources\AuditEventType.designer.tt file is created, but after that VS is stopped and automatically restarted. The project file is not modified.

I've updated the Resources.Designer.t4 for VS 2022 and retried, same issue..

![image](https://user-images.githubusercontent.com/126084/144595717-d62dd6f1-8975-48d1-9002-f90e0530b200.png)

This is logged in the event viewer:
`Naam van toepassing met fout: devenv.exe, versie: 17.0.31912.275, tijdstempel: 0x618f0853
Naam van module met fout: KERNELBASE.dll, versie: 10.0.22000.348, tijdstempel: 0x065c557a
Uitzonderingscode: 0xe0434352
Foutmarge: 0x000000000004478c
Id van proces met fout: 0x85b8
Starttijd van toepassing met fout: 0x01d7e83877adf4d9
Pad naar toepassing met fout: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: 52c6782e-fbba-455b-89a4-e641d0b295ee
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: `

**Comment by mdissel** [comment] 2021-12-03 13:17
I've created a new Class Library (.NET framework) and executed the same steps. Same error..

**Comment by tom-englert** [comment] 2021-12-06 06:57
Duplicate of #437

**Comment by tom-englert** [comment] 2021-12-06 06:58
The text templates engine is part of VisualStudio, not RXRM. There is nothing RXRM can do about this.

**Closed by tom-englert** 2021-12-06 06:58 UTC
Labels: duplicate
